### ISSUE TITLE
Add full example files to repository

### ISSUE THREAD

**Issue by lewismc** [ESIPFed/science-on-schema.org#10]
Hi @fils @ashepherd can one of you please upload complete sample files for both DataRepository and Dataset.
I suggest that we link to these at the very end of both guideline documents.

**Comment by ashepherd** [comment]
@lewismc , will do. thanks for the reminder!

**Comment by ashepherd** [comment]
Added examples into [/examples](https://github.com/ESIPFed/science-on-schema.org/tree/master/examples) directory. We should probably review, so I'll keep the issue open.

**Comment by ashepherd** [comment]
Fixed in https://github.com/ESIPFed/science-on-schema.org/commit/b3135cdc498b111dd0f2ab7eacc9ddfe6981d892
