### ISSUE TITLE
Adopt `funding` property if it gets accepted

### ISSUE THREAD

**Issue by ashepherd** [ESIPFed/science-on-schema.org#109]
https://github.com/schemaorg/schemaorg/pull/2618

**Comment by smrgeoinfo** [comment]
I think the property is 'funding', not 'funded'

**Comment by smrgeoinfo** [comment]
note [DINGO](https://figshare.com/articles/journal_contribution/DINGO_ontology_for_projects_and_grants/7479851) "an ontology expressly designed to provide an extensible interoperable framework for formally conceptualizing and expressing the relevant parts of the research/cultural landscape in relation to funding,"

**Comment by ashepherd** [comment]
Port of #158 
-------
PROBLEM: No property from schema:Dataset to describe the funding award (schema:funder describes the Funding Agency).

PROPOSED SOLUTION:

There is a property, schema:fundedItem, on schema:Grant that links to the CreativeWork. Using JSON-LD 1.1 @reverse property, it's possible from a Dataset landing page to use the schema:fundedItem property. See: [schemaorg/schemaorg#383 (comment)](https://github.com/schemaorg/schemaorg/issues/383#issuecomment-808754261)

Example: https://json-ld.org/playground/#startTab=tab-table&json-ld=%7B%22%40context%22%3A%22http%3A%2F%2Fschema.org%2F%22%2C%22%40type%22%3A%22Dataset%22%2C%22%40id%22%3A%22urn%3Aexample%3Adataset%3A1%22%2C%22%40reverse%22%3A%7B%22fundedItem%22%3A%5B%7B%22%40id%22%3A%22urn%3Aexample%3Aaward%3A123456789%22%2C%22%40type%22%3A%22MonetaryGrant%22%2C%22name%22%3A%22NSF-123456789%22%7D%5D%7D%7D


```
{
  "@context": "http://schema.org/",
  "@type": "Dataset",
  "@id": "urn:example:dataset:1",
  "@reverse": {
    "fundedItem": [
      {
        "@id": "urn:example:award:123456789",
        "@type": "MonetaryGrant",
        "name": "NSF-123456789"
      }
    ]
  }
}
```

generates RDF triples:

```
<urn:example:award:123456789> <http://schema.org/fundedItem> <urn:example:dataset:1> .
<urn:example:award:123456789> <http://schema.org/name> "NSF-123456789" .
<urn:example:award:123456789> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/MonetaryGrant> .
<urn:example:dataset:1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/Dataset> .
```

**Comment by mbjones** [comment]
Several groups are converging on a shared structure, including CodeMeta (https://github.com/codemeta/codemeta/issues/160), the EML 2.2.0 [`award`](https://eml.ecoinformatics.org/whats-new-in-eml-2-2-0.html#structured-funding-information) element, and the DataCite spec (see [example](http://schema.datacite.org/meta/kernel-4.0/example/datacite-example-fundingReference-v.4.0.xml), converged on a common set of fields for these grants. The discussion in CodeMeta has a good summary of the approaches. A few changes I would make, @ashepherd, would be to include the grant number and title, and the funder name and identifier.  All of that would be consistent with the CodeMeta proposal, and would look like this:

```json
{
  "@context": "http://schema.org/",
  "@type": "Dataset",
  "@id": "urn:example:dataset:1",
  "@reverse": {
    "fundedItem": [
      {
        "@id": "https://www.nsf.gov/awardsearch/showAward?AWD_ID=1546024",
        "identifier": "1546024",
        "name": "Scientia Arctica: A Knowledge Archive for Discovery and Reproducible Science in the Arctic",
        "url": "https://www.nsf.gov/awardsearch/showAward?AWD_ID=1546024",
        "funder": {
            "@id": "https://doi.org/10.13039/00000001",
            "@type": "Organization",
            "name": "National Science Foundation"
        } 
      }
    ]
  }
}
```

When parsed, this produces the following triples:
```
<https://doi.org/10.13039/00000001> <http://schema.org/name> "National Science Foundation" .
<https://doi.org/10.13039/00000001> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/Organization> .
<https://www.nsf.gov/awardsearch/showAward?AWD_ID=1546024> <http://schema.org/fundedItem> <urn:example:dataset:1> .
<https://www.nsf.gov/awardsearch/showAward?AWD_ID=1546024> <http://schema.org/funder> <https://doi.org/10.13039/00000001> .
<https://www.nsf.gov/awardsearch/showAward?AWD_ID=1546024> <http://schema.org/identifier> "1546024" .
<https://www.nsf.gov/awardsearch/showAward?AWD_ID=1546024> <http://schema.org/name> "Scientia Arctica: A Knowledge Archive for Discovery and Reproducible Science in the Arctic" .
<https://www.nsf.gov/awardsearch/showAward?AWD_ID=1546024> <http://schema.org/url> <https://www.nsf.gov/awardsearch/showAward?AWD_ID=1546024> .
<urn:example:dataset:1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/Dataset> .
```

**Comment by elishawc** [comment]
does it make sense to include RORs?
e.g., NSF - https://ror.org/021nxhr62

**Comment by smrgeoinfo** [comment]
I think that would be a good identifier to use.  The DOI in Matt's example is a dummy (doesn't resolve)
steve

**Comment by smrgeoinfo** [comment]
I must confess that while the @reverse works technically, it seems to me that it will be confusing to many people...  
Doesn't look like Google Rich REsults test recognizes the @Reverse...
https://search.google.com/test/rich-results?utm_campaign=sdtt&utm_medium=code&id=mMe3UTdWdPLJnHGY4ZcteQ

**Comment by mbjones** [comment]
@elishawc Thanks. The DOI in my example was not meant to be a dummy -- it was from the [CrossRef Funder Registry](https://www.crossref.org/education/funder-registry/), and I made a typo in my example, which is now fixed. The ID is http://dx.doi.org/10.13039/100000001, which is nice because all of the metadata is already in an RDF graph. That said, I think using a ROR is a good idea too, and I added that to the example above as well. So both are now updated.

@smrgeoinfo I agree it is a bit awkward, but it it is a legit feature of JSON-LD and one that validates well. Is there an alternative, given that the inverse property of `fundedItem` is not defined in schema.org?

**Comment by mbjones** [comment]
I also noticed that I somehow missed the `MonetaryGrant` type from @ashepherd 's example and so I added that back in. One issue for me was whether the example is ok using the "identifier" field as literals or whether we should use the structure we provided for other DOI and related identifiers?

**Comment by mbjones** [comment]
Discussed on the SOSO call from 2021-05-03, agreed that using `@reverse` on `fundedItem` will work for the time being, and that if schema.org agrees to an inverse property, we will shift to recommending that. Also, we all agreed it would be good to voice support for `funding` in schema.org (although possibly better named as `fundedBy`) in the PR on the issue: https://github.com/schemaorg/schemaorg/pull/2618 

TODO: Matt to writeup guidance docs, and ADR, and a PR for everyone to review.

**Comment by mbjones** [comment]
I edited Funding as we discussed, which is all on the [`feature_109_funding`](https://github.com/ESIPFed/science-on-schema.org/tree/feature_109_funding) branch, including the following:

- Revised [Dataset Funding](https://github.com/ESIPFed/science-on-schema.org/blob/feature_109_funding/guides/Dataset.md#funding) section
- Funding ADR (https://github.com/ESIPFed/science-on-schema.org/blob/feature_109_funding/decisions/109-funding.md)

Please comment on the PR or in this issue. Thanks!

**Comment by elishawc** [comment]
I see an award landing page field. 
Is there also a DOI field for the award? DOE is starting to issues DOIs for proposals as well.

**Comment by mbjones** [comment]
@elishawc Our convention for an award DOI would be to add it to the `schema:identifier` field. There can be multiple identifiers, so if someone has both an award number from an agency and a DOI for that award, they could both be included.

**Comment by datadavev** [comment]
Using `@reverse` is logically no different from using `@graph`, and both serialize to the same n-quads for example. An appropriate action for a consumer interpreting the content as a JSON representation of a Dataset may be to frame the document accordingly, for example [in JSON-LD playground](https://tinyurl.com/ydrftqux). Note the example defines `fundedItem` as a node identifier since that item is not yet defined in the SO context. (Note also that you need to click on another tab like "Expanded", then back to "Framed" to actually apply the frame.)

**Comment by mbjones** [comment]
Merged the PR into `develop`, so funding work is now ready for release.

**Comment by mbjones** [comment]
schema.org just added `funding` to the release. I suggest we switch to it in the guidelines.

**Comment by ashepherd** [comment]
https://github.com/schemaorg/schemaorg/issues/3056
