### ISSUE TITLE
Update the GOVERNANCE & README to list the ESIP Schema.org Cluster meeting times

### ISSUE THREAD

**Issue by ashepherd** [ESIPFed/science-on-schema.org#111]
1. GOVERNANCE.md is out of date with meeting information
2. We should put the meeting information front and center on the README for the repository

Telecons via [GoToMeeting](https://global.gotomeeting.com/join/431083909): 
Access Code: 431-083-909
Phone Access: United States: +1 (786) 535-3211
1st Monday at 5pmET 
4th Thursday, 2:30pmET

Telecon AGENDA Google doc: https://docs.google.com/document/d/1tIlDVnKeocO1E_SSbNaldv0avORfGFdmYDNk_3ub6ik/edit?ts=5d9ed12d

**Comment by mbjones** [comment]
I updated meeting info in the `develop` branch in sha f58a750110d0fe18dddacb6a168f85546840d20e for GOVERNANCE.md and in sha 5f04958f30a6f1697f4f3f55afe7143337795ec8 for README.md. This closes #111, and I also restructured the readme and provided more background info as a start on issue #127.

These changes are staged in `develop` and will be released to `master` with the 1.2 release. @ashepherd please review if you have a chance, but I don't think anything is controversial here.
