### ISSUE TITLE
full example document contain errors

### ISSUE THREAD

**Issue by mbjones** [ESIPFed/science-on-schema.org#115]
The [full example document](https://github.com/ESIPFed/science-on-schema.org/blob/master/examples/dataset/full.jsonld) does not fully follow the guidelines. The SHACL validator reports four errors:

- uses https instead of http namespace (won't fix as we changed the policy here for 1.2)
- the `identifier` should be of type `PropertyValue`
- the `sameAs` property is missing
- the `isAccessibleForFree` property is missing

I will directly check in a fix for these to the `develop` branch for the next release (1.2).

In addition, the document types the [`schema:description`](https://schema.org/description) field as `"@type": "HTML",`, which is not valid, and should be `Text`. This is not picked up by the SHACL validator. Can we make the validator find all undefined types and flag them, and flag when the type is not one of the recommended ones for a property in SO?

**Comment by mbjones** [comment]
Fixed in SHA 40343e0d1cd8dbf836d3b7c770900b29b2e9ef8a, but let's discuss the issue with not finding the HTML type mismatch via SHACL @datadavev

**Comment by ashepherd** [comment]
HTML is defined in the context here on line 5: https://schema.org/docs/jsonldcontext.json.txt

**Comment by mbjones** [comment]
Interesting, Adam. I thought the official context file is at: https://schema.org/version/latest/schemaorg-current-https.jsonld

Which doesn't seem to have `HTML`. Is the file you cited an earlier version? Maybe I need to clarify where the official context files are. I got them from this page that has links in different formats: https://schema.org/docs/developers.html#defs

**Comment by ashepherd** [comment]
very well may be *wicked* old apparently! Let's go with the official context cited on the developers page.

**Comment by datadavev** [comment]
JSON-LD remote context retrieval is described in https://www.w3.org/TR/json-ld11-api/#context-processing-algorithms

In brief, for schema.org, a context written:

```
{
   "@context":"http://schema.org/", 
   ... 
}
```

invokes the following sequence for the json-ld processor:

```
> GET "Accept: application/ld+json" "http://schema.org/"
< 301 "Location: https://schema.org/"

> GET "Accept: application/ld+json" "https://schema.org/"
< 200 Link: </docs/jsonldcontext.jsonld>; rel="alternate"; type="application/ld+json"

> GET "Accept: application/ld+json" "https://schema.org/docs/jsonldcontext.jsonld"
{
  "@context": {
    "type": "@type",
    "id": "@id",
    "HTML": {
      "@id": "rdf:HTML"
    },
  ...
```
(i.e., the context document is actually at `https://schema.org/docs/jsonldcontext.jsonld`)

Therein, `HTML` is mapped to `rdf:HTML`, which expands to `http://www.w3.org/1999/02/22-rdf-syntax-ns#HTML`.

The vocabulary is a separate document that identifies the relationships of terms identified in the context. It is located at:

* http namespace version: https://schema.org/version/latest/schemaorg-current-http.jsonld
* https namespace version: https://schema.org/version/latest/schemaorg-current-https.jsonld

Equivalence mappings between the `http` and `https` terms was added recently (not yet available on the production site) at: https://github.com/schemaorg/schemaorg/blob/http-httpsequivs/data/releases/9.0/schemaorg-http-https-equivalents.jsonld

**Comment by mbjones** [comment]
Based on @datadavev 's synopsis, is there anything remaining here? Seems like this ticket can be closed if we are happy with the context resolution.

**Comment by mbjones** [comment]
I checked and restored the `HTML` type to the document as per the comment by @datadavev above, and pushed to `develop`. So this issue is complete and closed.
