### ISSUE TITLE
"ResearchProject" and "Service" are not types known to Google

### ISSUE THREAD

**Issue by lewismc** [ESIPFed/science-on-schema.org#12]
We know that the Google [Structure Data Testing Toool](https://search.google.com/structured-data/testing-tool/u/0/) is maybe not in sync with how Google is actually interpreting schema.org JSON-LD markup, however I think this is something we should really clarify.

Right now when I use the tool, I am prompted with various warnings stating that either Service and/or ResearchProject are not types known to Google.

I know that [ResearchProject](https://pending.schema.org/ResearchProject) is pending however [Service](https://schema.org/Service) is not! Service has been part of schema.org for ages.

**Comment by johardi** [comment]
I checked the Google testing tool today and didn't get the error message about the Service type. I think the tool is finally in sync with the current schema.

**Comment by lewismc** [comment]
Thanks @johardi I'll scope it out today as well and see what results I get.

**Comment by lewismc** [comment]
@johardi ok so here are my findings...
`ResearchProject` is still not recognized as a type but you are correct in that `Service` now is which is great. There are some **warnings** with `Service` however...
| schema.org key     | value                                            | Tool Warning                                                                               |
|--------------------|--------------------------------------------------|--------------------------------------------------------------------------------------------|
| foundingDate       | 1978-01-01                                       | The property foundingDate is not recognised by Google for an object of type Service        |
| legalName          | Physical Oceanography Data Active Archive Center |  (The property legalName is not recognised by Google for an object of type Service.)       |
| address            | NESTED OBJECT                                    | The property address is not recognised by Google for an object of type Service.            |
| contactPoint       | NESTED OBJECT                                    | The property contactPoint is not recognised by Google for an object of type Service.       |
| funder             | NESTED OBJECT                                    | The property funder is not recognised by Google for an object of type Service.             |
| parentOrganization | NESTED OBJECT                                    | The property parentOrganization is not recognised by Google for an object of type Service. |

**Comment by lewismc** [comment]
The JSON-LD I am using here BTW can be found [here](https://github.com/lewismc/podaac.geosci.schema.org/blob/master/DataRepository.jsonld)

**Comment by lewismc** [comment]
Some other tooling to possibly help us out
http://www.seoskeptic.com/structured-data-markup-validation-testing-tools/

**Comment by ashepherd** [comment]
It looks like ResearchProject is now recognized.
