### ISSUE TITLE
Update recommendation of Dataset keywords to use DefinedTerm

### ISSUE THREAD

**Issue by ashepherd** [ESIPFed/science-on-schema.org#125]
https://schema.org/keywords
https://schema.org/DefinedTerm

Dataset Overview diagram: https://lucid.app/lucidchart/ab057bb0-692e-4034-adc5-b7e76e84fd37/edit?page=0_0#?folder_id=home&browser=icon

**Comment by mbjones** [comment]
Consider whether `schema:PropertyValue` would be a better alternative, as it allows definition of both the property IRI and the value IRI, whereas with `DefinedTerm` may not be as explicit about the predicate IRI.

**Comment by mbjones** [comment]
Given that we haven't worked out these DefinedTerm changes, and there seems to be more to be discussed from our last call, I am going to retarget this at milestone 1.3.

**Comment by ashepherd** [comment]
+1 for v1.3 

I think since schema.org lets you specify a DefinedTerm and repositories in geosciences already are using defined terms (like GCMD keywords, NERC Vocabulary server), we should at least guide folks how to do this

**Comment by smrgeoinfo** [comment]
+1 for 1.3

**Comment by ashepherd** [comment]
To-DO (ESIP Summer Meeting):

1) `@id` for any resolvable machine-readable description for a term.

2) `url` for any non machine-0readable URL for a term

3) `inDefinedTermSet` needs more clarity - text, uris, etc.

4) Ready for Pull request proposal

**Comment by mbjones** [comment]
I noticed that this change caused our SHACL validation rules to fail, so I updated the SOSO rules in sha f5e3c4825d8 to allow the `schema:keywords` to be a `sh:Literal` as was previously allowed, OR a `schema:DefinedTerm` as the current guidelines in 1.3 recommend. @fils or @datadavev or @ashepherd some additional eyeballs on this new SHACL rule would be welcome. See [soso_common_v1.2.3.ttl#L128](https://github.com/ESIPFed/science-on-schema.org/blob/develop/validation/shapegraphs/soso_common_v1.2.3.ttl#L128).

**Comment by datadavev** [comment]
The shape would not validate a test case until edited as in 62677e7 (i.e. moving minCount and path outside or).

**Comment by mbjones** [comment]
Thanks, that looks good. I tried it with an online validator (https://shacl-playground.zazuko.com/) and I see some weird results.  

## Validate correctly

The following validate, as expected:

1. Array of literals
```json
"keywords": ["foo", "bar"],
```

2. Array of DefinedTerm
```json
  "keywords": [
    {
    "@type": "DefinedTerm",
    "name": "key1",
    "inDefinedTermSet": "vocab1"
    }
  ],
```

3. Array of Literal and DefinedTerm
```json
  "keywords": [ "foo",
    {
    "@type": "DefinedTerm",
    "name": "key1",
    "inDefinedTermSet": "vocab1"
    }
  ],
```

4. Array of DefinedTerm with multiple entries
```json
  "keywords": [
    {
    "@type": "DefinedTerm",
    "name": "key1",
    "inDefinedTermSet": "vocab1"
    },
    {
    "@type": "DefinedTerm",
    "name": "key2",
    "inDefinedTermSet": "vocab1"
    }
  ],
```

## Do not validate correctly

5. Array of Literal and "NotDefinedTerm" object
This next one doesn't validate, but I would expect it to pass the `sh:Literal` test. Not sure why it doesn't.

```json
  "keywords": ["foo",
    {
    "@type": "NotDefinedTerm",
    "name": "key1",
    "inDefinedTermSet": "vocab1"
    }
  ],
```

6. Array of `DefinedTerm` and another object `NotDefinedTerm`
The next one does not validate, but I would expect it to pass the `sh:class` test given that it has one proper `schema:DefinedTerm`, but it doesn't. It seems if any member of the array is not a proper DefinedTerm, then it fails.

```json
  "keywords": [
    {
    "@type": "DefinedTerm",
    "name": "key1",
    "inDefinedTermSet": "vocab1"
    },
    {
    "@type": "NotDefinedTerm",
    "name": "key2",
    "inDefinedTermSet": "vocab1"
    }
  ],
```

Do you get these same results with pyshacl?

**Comment by smrgeoinfo** [comment]
Looks like 5 and 6 are similar-- an array of values in which one is invalid.

**Comment by datadavev** [comment]
I think that's the correct behavior, or at least it is consistent with observations with different SHACL processors - 5 and 6 should not validate since the SHACL specifies each value node conforms to at least one of the provided shapes.

**Comment by mbjones** [comment]
ok, that makes sense. Thanks for the clarification. I think we can close this issue.
