### ISSUE TITLE
Restructure README to provide better context

### ISSUE THREAD

**Issue by mbjones** [ESIPFed/science-on-schema.org#127]
The current README.md provides good background on historical releases and the project, but could be improved by:

1) provide better context about what the guidelines are for
2) Make the main Guidelines documents more prominent and clear what they are for, and how to cite them
3) Potentially include links/pointers to other SDO and Dataset level primers, such as the one pointed out by Chantelle 
4) Lower the prominence of historical/project related information and other ancillary information
5) other miscellaneous copyedit and cleanup for clarity and better communication

Anything else?

**Comment by mbjones** [comment]
In #111, I did a basic README restructure covering some aspects of points (1), (2), (4), and (5) above. More could be done, but this is a start. 

@ashepherd I see you moved this to milestone v1.2, whereas I had covered the changes for v1.2 under issue #111. As I didn't think we were ready with in particular point (3) from above about links to other primers, I had targeted this at 1.3. Is it ok to move it back there?

**Comment by ashepherd** [comment]
oh sure! my bad. i thought you wanted those changes for this release. I switched it back to 1.3

**Comment by ashepherd** [comment]
+1 for v1.3 will be useful as part of the ESIP Endorsement

**Comment by ashepherd** [comment]
space b/w pm and ET

```
1st Monday at 5pm ET
4th Thursday, 2:30pm ET
```

**Comment by ashepherd** [comment]
from Melinda:

Add a contextual description for each Resource as to why it's relevant. Just as text immediately after the link

**Comment by ashepherd** [comment]
from Ryan:

close to GETTING STARTED , add a sentence or two as to who these guidelines are for

**Comment by ashepherd** [comment]
Maybe try elevating the guidance docs like BioSchemas (https://bioschemas.org/profiles/)

Table of Guidance doc, its issues, examples, etc.

- maybe not use icons
- ask Leyla at Bioschemas if people find having grouped issues per guidance/profile helpful
