### ISSUE TITLE
Announce the v1.2.0 release

### ISSUE THREAD

**Issue by ashepherd** [ESIPFed/science-on-schema.org#145]
- [x] Write intro sentences (abbrev. version of README text)
- [x] esip-schema-org, (Adam)
- [x] esip-all, (Adam)
- [x] RDA research-metadata-schemas, (Adam)
- [x] polar data group,  (Matt)
- [x] LTER IM, (Matt)
- [x] DataONE, (Matt)
- [x] agu-essi,  _(via Twitter)_
- [x] [CANLIB-DATA](https://researchdata.library.ubc.ca/learn/canlib-data-listserv/) , _(via Twitter)_
- [x] Dataverse,  _(via Twitter)_
- [x] W3C Schemaorg mailing list,  _(via Twitter)_

-----------------
Email Text Below
-----------------

On behalf of the Schema.org cluster at ESIP, we are pleased to announce the latest version of the Science-on-schema.org publishing guidelines. These guidelines describe how to publish consistent and FAIR schema.org markup for Datasets. Stewarded by members of the ESIP Schema.org cluster, version 1.2.0 was developed in collaboration with other data repository operators and Schema.org project members. 

**Guidelines**:  https://science-on-schema.org

**DOI**: [10.5281/zenodo.4477164](https://doi.org/10.5281/zenodo.4477164)

**Citation**: Matthew B. Jones, Stephen Richard, Dave Vieglais, Adam Shepherd, Ruth Duerr, Doug Fils, Lewis McGibbney. (2021). Science-on-Schema.org v1.2.0 (Version 1.2.0). Zenodo. https://doi.org/10.5281/zenodo.4477164

**Contributors**: Adam Leadbetter, Dan Brickley, Richard Wallis.

## RELEASE NOTES
-----------
**FIXES**

* Fix various errors in <a href="http://github.com/ESIPFed/science-on-schema.org/blob/1.2.0/examples/dataset/full.jsonld" target="_blank">Dataset full example</a> JSON-LD (<a href="https://github.com/ESIPFed/science-on-schema.org/issues/115" target="_blank">Issue #115</a>)
    * the `identifier` should be of type `PropertyValue`
    * the `sameAs` property is missing
    * the `isAccessibleForFree` property is missing

**IMPROVEMENTS**

* Improvements for describing geospatial coverage (<a href="http://github.com/ESIPFed/science-on-schema.org/blob/1.2.0/decisions/101-spatialExtent.md" target="_blank">decision</a>, <a href="https://github.com/ESIPFed/science-on-schema.org/issues/101" target="_blank">Issue #101</a>)
* Dataset Provenance for processing workflows, data derivation, and dataset versioning (<a href="http://github.com/ESIPFed/science-on-schema.org/blob/1.2.0/decisions/72-provenance.md" target="_blank">decision</a>, <a href="https://github.com/ESIPFed/science-on-schema.org/issues/72" target="_blank">Issue #72</a>)
    * <a href="https://github.com/ESIPFed/science-on-schema.org/blob/1.2.0/guides/Dataset.md##provenance-relationships" target="_blank">Guide: Dataset - Provenance Relationships</a>
* Use `schema:dateModified`for announcing when a Dataset resource has changed (<a href="https://github.com/ESIPFed/science-on-schema.org/issues/67" target="_blank">Issue #67</a>)
    * <a href="https://github.com/ESIPFed/science-on-schema.org/blob/1.2.0/guides/Dataset.md#howmodification_times">Guide: Dataset - Time of resource modification</a>
* How to reference a short DOI (<a href="https://github.com/ESIPFed/science-on-schema.org/issues/120" target="_blank">Issue #120</a>)
    * <a href="https://github.com/ESIPFed/science-on-schema.org/blob/1.2.0/guides/Dataset.md#how-to-reference-short-dois" target="_blank">Guide: Dataset - How to reference Short DOI</a>
* Update GOVERNANCE &amp; README to list ESIP Schema.org Cluster meeting times (<a href="https://github.com/ESIPFed/science-on-schema.org/issues/111" target="_blank">Issue #111</a>)

**NEW FEATURES**

* Add SHACL shape to validate schema.org namespace (<a href="http://github.com/ESIPFed/science-on-schema.org/blob/1.2.0/decisions/52-namespace-consistency.md" target="_blank">decision</a>, <a href="https://github.com/ESIPFed/science-on-schema.org/issues/59" target="_blank">Issue #59</a>)

**Comment by ashepherd** [comment]
@mbjones , text ok?

**Comment by mbjones** [comment]
Looks good to me. Nitpick -- the `Authors` is redundant with `Citation` and can probably be removed. But looks good either way.

**Comment by ashepherd** [comment]
Good point! I’ll take that out and move Contributors underneath the citation.

**Comment by mbjones** [comment]
@ashepherd  I edited it in the text above and will hit the lists that I indicated above. I'm happy to hit some more lists too if you'd like, but thought I would start there.

**Comment by ashepherd** [comment]
Tweeted to all the folks: https://twitter.com/ScienceOnSchema/status/1359171303027146757

mentions ```
@ESIPfed
@resdatall
@ESSI_AGU
@dataverseorg
@SchemaOrg
@LibraryArchives
@DataONEorg
@USLTER```
