### ISSUE TITLE
Describe the Grant funding a Dataset

### ISSUE THREAD

**Issue by ashepherd** [ESIPFed/science-on-schema.org#158]
PROBLEM: No property from schema:Dataset to describe the funding award (schema:funder describes the Funding Agency). 

PROPOSED SOLUTION: 
1. There is a property, schema:fundedItem,  on schema:Grant that linksto the CreativeWork. Using JSON-LD 1.1 `@reverse` property, it's possible from a Dataset landing page to use the schema:fundedItem property. See:

https://github.com/schemaorg/schemaorg/issues/383#issuecomment-808754261

Example: https://json-ld.org/playground/#startTab=tab-table&json-ld=%7B%22%40context%22%3A%22http%3A%2F%2Fschema.org%2F%22%2C%22%40type%22%3A%22Dataset%22%2C%22%40id%22%3A%22urn%3Aexample%3Adataset%3A1%22%2C%22%40reverse%22%3A%7B%22fundedItem%22%3A%5B%7B%22%40id%22%3A%22urn%3Aexample%3Aaward%3A123456789%22%2C%22%40type%22%3A%22MonetaryGrant%22%2C%22name%22%3A%22NSF-123456789%22%7D%5D%7D%7D

**Comment by mbjones** [comment]
Added to the 1.3 board. How does this ticket relate to #109?

**Comment by ashepherd** [comment]
This really should've been on issue #109 . Ok to migrate the proposed solution to that pre-existing issue, and close this one?
