### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by ashepherd** [ESIPFed/science-on-schema.org#16]
Ok, we picked the name `science-in-schema.org` quickly and without using our brains. I feel it's a little pretentious and not respecting other science disciplines and efforts in the schema.org space (e.g. bioschemas.org). 

Any thoughts?

**Comment by lewismc** [comment]
@ashepherd what about `geosci.schema.org`?

**Comment by ashepherd** [comment]
ah, I like it. but, if we wanted to mint our own properties, we would have to go through schema.org first. maybe we can pick another domain too? @fils did you have a domain already? 

Or we can punt and just change the name of this repo

**Comment by lewismc** [comment]
@ashepherd aye that's an excellent point. I don't know to be honest.

**Comment by mbjones** [comment]
https://geoschemas.org ?  Is that you already there, @ashepherd ?   The format looks familiar.

**Comment by ashepherd** [comment]
Yeah, we needed a stable URL to host any potential schema.org extensions. I threw that up quickly with a copy of schema.geolink.org, but the plan is to move that to Jekyll here in a new Github repo under ESIP. But, maybe we repurpose this repository and kill two birds with one stone? I didn't mean to step on toes by claiming all science. Thoughts?

**Comment by mbjones** [comment]
Honestly, I wasn't that worried about 'claiming all science'.  But it would be nice to not have discipline bounds on what kind of extensions are in scope.  Many of the extensions we are proposing (like how to link to associated metadata records in #4) are not specific to geo.  An alternative might be `esipschemas.org`? Or `scienceschemas.org`?

**Comment by ashepherd** [comment]
That's a very good point. Maybe we wait until RDA 14 when Mingfang's schema.org WG gets off the ground to determine the right place for general science recommendations and geo-specific recommendations.

**Comment by lewismc** [comment]
Also, ideally we would want the domain to be minted for a decent length of time (10 years) as is done with sweetontology.net & .org. ESIP owns these. We convinced ESIP to purchase and own these domains.

**Comment by ashepherd** [comment]
nice, I grabbed geoschemas.org for 10 yrs as well, but happy to transfer 
that elsewhere. Just didn't want to miss an opportunity.

**Comment by lewismc** [comment]
OK great. That sounds good @ashepherd

**Comment by lewismc** [comment]
@ashepherd I'm registering this AGU session right now. Will I just use the name geoschemas.org ?

**Comment by ashepherd** [comment]
Ah maybe we still use science-on-schema.org since others are talking about that? I’m terrible at these strategic decisions so i defer to whatever you think is best.

————————————————
Adam Shepherd
Woods Hole Oceanographic Institution
email:ashepherd@whoi.edu
voice: 508.289.2772
ORCID: 0000-0003-4486-9448

Technical Director
Biological and Chemical Oceanography Data Management Office
 ————————————————
https://www.linkedin.com/in/ashep15/
https://www.bco-dmo.org

**Comment by charlesvardeman** [comment]
I had a thought last week that maybe having two repositories could be useful for different purposes. I don't believe the existing science-on-schema.org has any new vocabulary as of yet but exists mainly of examples for integrating schema.org datasets at the repository level. I think having an effort that is giving examples and provides a place to go when getting into the schema.org weeds for the sciences is VERY important, and could be broader than just the earth sciences. Then having a second geoshemas.org that is similar to bioschemas.org that provides the geo-specific extensions to schema.org would make sense. The only purpose of geoschemas.org would be then to vet and discuss new vocabulary and publish that new vocabulary as community driven extensions to schema.org.
