### ISSUE TITLE
Create DOI for repository

### ISSUE THREAD

**Issue by lewismc** [ESIPFed/science-on-schema.org#17]
We should generate a release for the repository and generate a DOI with Zenodo. This will be required for us to push through an ESIP endorsement for the work.

**Comment by ashepherd** [comment]
Got it. Need to add you and Beth as co-authors. If you want to send me your ORCiDs?

https://doi.org/10.5281/zenodo.2628755 (series DOI)

**Comment by lewismc** [comment]
@ashepherd 
orcid.org/0000-0003-2185-928X

**Comment by ashepherd** [comment]
done. happy to add Beth too
