### ISSUE TITLE
Create and submit ESIP endorsement document to ESIP ExCom

### ISSUE THREAD

**Issue by lewismc** [ESIPFed/science-on-schema.org#18]
In order to have ESIP endorse this effort, we need to work on the following
```
1.7.1 Proposing Endorsements

Any Representative of the Assembly may propose an ESIP endorsement. 
Proposals shall be submitted in writing (e.g., email) to the Chair of the ESIP Program 
Committee prior to any action on the proposed endorsement. 
The Proposal shall include a history of the work or issue and a statement 
describing why it is of benefit for ESIP to endorse the product, service or statement.
```
... this is stated [here](https://github.com/ESIPFed/Governance/blob/master/ESIP%20Policies%20and%20Procedures/1.0%20Corporate/ESIP%20P%26P%201.7%20Endorsements.md)

I went ahead and [started a document](https://docs.google.com/document/d/1O539ROr9W7FUEDzR2ni2H2Doxx_2zK8AF-sma8pBDe0/edit?usp=sharing)

**Comment by bethhuffer** [comment]
Thanks for getting this started, Lewis!

**Comment by mbjones** [comment]
Agreed at our January 2021 call to target the Summer 2021 ESIP meeting to prepare and submit this guidance document for SOSO for ESIP-wide endorsement.

**Comment by ashepherd** [comment]
updating with a Google doc link
https://docs.google.com/document/d/1O539ROr9W7FUEDzR2ni2H2Doxx_2zK8AF-sma8pBDe0/edit?pli=1#

**Comment by ashepherd** [comment]
Draft the following content:

1. Compelling Argument (concise)
2. History of how we got here

**Comment by ashepherd** [comment]
1. Decided with Megan and Chantelle to keep the guidelines in Github.
2. The Endorsement document will reference pointers into the Github repo. (these should be long-lived to the version we are endorsing => v1.3)

**Comment by lewismc** [comment]
Nice @ashepherd
