### ISSUE TITLE
Confirm Author List for the Endorsement Document

### ISSUE THREAD

**Issue by ashepherd** [ESIPFed/science-on-schema.org#195]
1. All Schema.org Cluster members attending a call, etc. should at least be asked. 
2. All authors from previous versions of the guidelines should be included (with an opt-out)

**Comment by mbjones** [comment]
We worked out authorship and contributor status for the v1.3 release in issue #201 and during cluster meetings, which is now reflected in the citation for the release in the README. I updated the endorsement document with the agreed citation.
