### ISSUE TITLE
Compelling Argument paragraph for Endorsement document

### ISSUE THREAD

**Issue by ashepherd** [ESIPFed/science-on-schema.org#196]
Endorsement include short concise paragraph on why this is compelling

Related to #18

**Comment by mbjones** [comment]
I proposed revisions to the "Benefits of Endorsement" paragraph that I hope address this issue, and allow us to close it. Please review and comment in the Google doc for the endorsement: https://docs.google.com/document/d/1O539ROr9W7FUEDzR2ni2H2Doxx_2zK8AF-sma8pBDe0/edit?pli=1#
