### ISSUE TITLE
Get list of adopters/implementers to include in the Endorsement

### ISSUE THREAD

**Issue by ashepherd** [ESIPFed/science-on-schema.org#198]
Data providers/repositories:

- [x] BCO-DMO
- [x] DataONE
- [x] EarthCube 
- [x] POLDER
- [x] MAGIC
- [x] IODE
- [x] NASA
- [x] SOIL Informatics
- [x] Arctic Data Center
- [x] Netherlands Polar Data Center
- [x] Dryad
- [x] Hydroshare

Qualifier: These 'X' have expressed interest and intent, and some have implemented one of the guidelines. 

Data harvesters/aggregators:

- [x] DataONE
- [x] POLDER
- [x] GeoCodes
- [x] Google Dataset Seaerch

**Comment by mbjones** [comment]
We discussed the lsit of endorsers/implementors on the SOSO cluster call on 2020-06-06 and agreed that a representative list was sufficient for the endorsement. I updated the list of providers above. In addition, @datadavev suggested that a list of aggregators that utilize the SOSO guidelines would be good as well, and @mbjones added that list above and in the endorsement document. The endorsement document now reads as follows:

> In addition, a wide variety of programs and projects either have already adopted or are considering adopting these guidelines.  Groups publishing records using science on schema.org guidelines include [DataONE](https://www.dataone.org/), [EarthCube](https://www.earthcube.org/), [Polder](https://polder.info/), [MagIC](https://www.earthref.org/MagIC/), [IOC-UNESCO IODE](https://www.iode.org/), [NASA](https://www.nasa.gov/), [Soil Informatics](https://wiki.esipfed.org/Soil_Ontologies_and_Informatics), [BCO-DMO](https://www.bco-dmo.org/), [Arctic Data Center](https://arcticdata.io/catalog), [Netherlands Polar Data Center](https://npdc.nl/), [Dryad](https://datadryad.org/stash), and [Hydroshare](https://www.hydroshare.org/), among many others. In addition, several data networks and aggregators are now consuming science-on-schema.org based records to build federated search systems, including [DataONE](https://www.dataone.org/), [Polder](https://polder.info/), [GeoCodes](https://geocodes.earthcube.org/), and [Google Dataset Search](https://datasetsearch.research.google.com/).

Closing this issue as completed.
