### ISSUE TITLE
Different times associated with a dataset

### ISSUE THREAD

**Issue by dr-shorthair** [ESIPFed/science-on-schema.org#208]
Scientific datasets typically have multiple times associated, including
1. the time the dataset was generated (e.g. when the model was run; when data processing was completed; ...)
2. the time the phenomenon described in the dataset applies in the world (which is usually prior to 1. for observational data, and after for forecasts) 
3. the time the dataset is valid or recommended for use (esp. for forecasts)
4. ... many others - particularly in forecasting scenarios

[s:temporalCoverage](https://github.com/ESIPFed/science-on-schema.org/blob/master/guides/Dataset.md#temporal-coverage) appears to capture case 2.

I can't find a recommendation in the SoS documentation for case 1. or 3. 

For case 1., the recommendation for [recording workflows in SoS](https://github.com/ESIPFed/science-on-schema.org/blob/master/guides/Dataset.md#indicating-a-software-workflow-or-processing-activity-provused-and-provwasgeneratedby) uses ProvOne classes (derived from W3C Prov-O). This steps outside the Schema.org ecosystem. Would it make sense to remodel or present an alternative Schema.org-based model? If the observation or model run is conceived as a [s:CreateAction](https://schema.org/CreateAction) then perhaps [s:endTime](https://schema.org/endTime) applies. 

For case 3. [s:validThrough](https://schema.org/validThrough) has part of the required semantics (needs to be balanced with `s:validFrom`), but this property is not associated with [s:Dataset](https://schema.org/Dataset) or any [s:CreativeWork](https://schema.org/CreativeWork)

Note: in W3C SSN 
- case 1. is [sosa:resultTIme](https://www.w3.org/TR/vocab-ssn/#SOSAresultTime) 
- case 2. is [sosa:phenomenonTime](https://www.w3.org/TR/vocab-ssn/#SOSAphenomenonTime). 
 
SOSA does not handle `validTime` (OGC O&M does).

**Comment by smrgeoinfo** [comment]
Here's what schema.org offers for Thing>Dataset:

- dateCreated  :: match with 'the time the dataset was generated' 
- dateModified :: recommend this is used to specify when the dataset described by the metadata record was most recently updated. 
- datePublished :: use for when data (e.g. model results) are made available.
- contentReferenceTime -- The specific time described by a creative work, for works (e.g. articles, video objects etc.) that emphasize a particular moment within an Event.  :: this is obviously pretty hard to distinguish from 'temporalCoverage', I'd recommend avoiding unless someone can clarify the distinction.
- temporal -- used in cases where more specific properties (e.g. temporalCoverage, dateCreated, dateModified, datePublished) are not known to be appropriate.  :: not much use for SOSO, given that its not clear what it is supposed to mean....
- temporalCoverage --  the period that the content applies to. :: match with 'the time the phenomenon described in the dataset applies in the world' 
-   expires   Date the content expires and is no longer useful or available. :: less clear, but if published is when the model results are available, 'expires' can bracket 'the time the dataset is valid or recommended for use '
- sdDatePublished Indicates the date on which the current structured data was generated / published. ['structure data' appears to be google talk for the metadata record] :: useful for the metadata publication date, but in aggregating/harvesting metadata federation need to know the  metadata update date, and also need a unique identifier for the metadata record.

**Comment by dr-shorthair** [comment]
> - dateCreated :: match with 'the time the dataset was generated'
> - dateModified :: recommend this is used to specify when the dataset described by the metadata record was most recently updated.
> - datePublished :: use for when data (e.g. model results) are made available.
> - temporalCoverage -- the period that the content applies to. :: match with 'the time the phenomenon described in the dataset applies in the world'
> - expires Date the content expires and is no longer useful or available. :: less clear, but if published is when the model results are available, 'expires' can bracket 'the time the dataset is valid or recommended for use '

Thanks @smrgeoinfo that'll work. 

I'll create a separate issue for the provenance model.

**Comment by dr-shorthair** [comment]
Oh - should these be added into the documentation / recommendations?

**Comment by mbjones** [comment]
Merged PR #212 into `develop` with updated language after today's call. New section complete for 1.3 release.
