### ISSUE TITLE
Dataset checksum algorithm property is missnamed

### ISSUE THREAD

**Issue by ashepherd** [ESIPFed/science-on-schema.org#230]
`spdx:checksumAlgorithm` should be `spdx:algorithm`
See: https://spdx.org/rdf/terms/#d4e52

**Comment by mbjones** [comment]
Ug. Good catch. We discussed this here (https://github.com/ESIPFed/science-on-schema.org/issues/66#issuecomment-840090420) and missed the second error.

**Comment by mbjones** [comment]
This issue is complete with PR #234 being merged, so closing.
