### ISSUE TITLE
s3 distributions

### ISSUE THREAD

**Issue by valentinedwv** [ESIPFed/science-on-schema.org#237]
Have a provider that has data in s3, 
how should we suggest that they specify the endpoint.

https://wifire-data.sdsc.edu/dataset/872ba2a0-4e91-4a74-b2b4-21073a21ad7b/resource/bb5439a8-dd45-4046-97f9-496066ef2daf

**Comment by mbjones** [comment]
@valentinedwv Can you clarify what they are specifying the endpoint for? That URI, when I resolve it, leads to a page that might be a descriptor for a digital object that is part of this `Dataset`: https://wifire-data.sdsc.edu/dataset/fastfuels Is that correct? But the link to the containing resource seems to not work. In any case, if it is part of that `Dataset`, then in SOSO we would recommend documenting that relationship in the Dataset JSON-LD following the [Distributions](https://github.com/ESIPFed/science-on-schema.org/blob/master/guides/Dataset.md#distributions) convention, which basically say to provide the `contentURL` for download of a `DataDownload`. For an S3 object, the contentURL would likely be built from the object identifier and the S3 system from which it can be retrieved.
