### ISSUE TITLE
Flesh out a rich variable description of a dataset

### ISSUE THREAD

**Issue by ashepherd** [ESIPFed/science-on-schema.org#24]
Example could link to CF at NERC and units and other vocabs.

**Comment by steingod** [comment]
Is the idea is to support multiple vocabularies? So a structure supporting proper identification of the vocabulary/glossary used as well as the specific keyword used? AFAIK I understand the guidlines, these fields can be repeated? So it is not a unique element containing a list?

**Comment by edeediong** [comment]
Hi @ashepherd, I'm new to open source. How do I contribute to this issue?

**Comment by mbjones** [comment]
@edeediong I think the idea is to improve the guidelines that are currently here:

https://github.com/ESIPFed/science-on-schema.org/blob/master/guides/Dataset.md#variables

with a complete example from a real dataset.  The current example only shows a single `variableMeasured`, which is typically not the case.

In addition, it would be useful to determine which vocabularies should/could be used in `variableMeasured`, or issues with the existing guidelines such as the lack of a link to a controlled vocabulary for `unitText`.

**Comment by edeediong** [comment]
@mbjones Thanks so much. https://search.dataone.org/data is this where I can find the datasets? Saw it in the readMe file. I do apologize for not being available.

**Comment by ashepherd** [comment]
i wonder if we can close this issue since we update the example JSON-LD as a matter of course?

**Comment by ashepherd** [comment]
dependent on decisions made inn #27

**Comment by smrgeoinfo** [comment]
I think the @id http URIs in full.jsonld should be in propertyID, assuming they are intended to identify properties instead of the PropertyValue objects in the document?  If that's not controversial, perhaps we could at least update that in full.jsonld for upcoming release?
