### ISSUE TITLE
Reschedule 4th Thursday of Month Telecon for Nov and Dec 2019

### ISSUE THREAD

**Issue by ashepherd** [ESIPFed/science-on-schema.org#33]
Nov and Dec telecons fall on Thanksgiving and the day after Christmas. In anticipation of low attendance, we propose to reschedule for the 3rd Thursday at 3pm (to not conflict with other ESIP meetings on the [calendar](https://www.esipfed.org/get-involved/telecon-calendar)). The dates are Nov 21 & Dec 19.

All in favor??

**Comment by smrgeoinfo** [comment]
+1

**Comment by rduerr** [comment]
I can't attend Nov 21 - will be in Finland for Polar data summit

**Comment by ashepherd** [comment]
ok, i emailed Megan and Dan to see if we could move the dates for Nov & Dec

**Comment by ashepherd** [comment]
rescheduled by Dan Keyes to Nov 21 and Dec 19 at 3pmET
