### ISSUE TITLE
ESIP Testbed Proposal Due 1/10/2020

### ISSUE THREAD

**Issue by ashepherd** [ESIPFed/science-on-schema.org#54]
IDEA #1 Review of Widoco doc ontology - its use of schema.org, 
This proposal would recommend suggestions for describing an ontology using schema.org

URL: http://dgarijo.github.io/Widoco/
EXAMPLE: http://linked.earth/ontology/core/1.2.0/index-en.html#CalibrationModel 
```<!-- SCHEMA.ORG METADATA -->
<script type="application/ld+json">{"@context":"http://schema.org","@type":"TechArticle","url":"http://linked.earth/ontology#","image":"http://vowl.visualdataweb.org/webvowl/index.html#iri=http://linked.earth/ontology#","name":"The LiPD Ontology", "headline":"The Linked Earth Ontology aims to provide a common vocabulary for annotating paleoclimatology data", "datePublished":"4 April 2017", "version":"1.2.0", "license":"http://creativecommons.org/licenses/by/2.0/", "author":[{"@type":"Person","name":"Nick McKay","url":"http://www.cefns.nau.edu/~npm4/"},{"@type":"Person","name":"Julien Emile-Geay","url":"http://orcid.org/0000-0001-5920-4751"},{"@type":"Person","name":"Deborah Khider","url":"http://earth.usc.edu/~khider/"}], "contributor":[{"@type":"Person","name":"Yolanda Gil","url":"http://www.isi.edu/~gil/"},{"@type":"Person","name":"Daniel Garijo","url":"http://w3id.org/people/dgarijo"}]}</script>
```

Another possible partner: Nic Carr of pyLODE 
https://github.com/rdFLib/pyLODE is a Python implementation of LODE - developed to provide an alternative to LODE Online Service because that is not always up. 

@datadavev @rduerr

**Comment by lewismc** [comment]
Hi @ashepherd this is an excellent idea. We discussed this on the COR side as well see https://github.com/mmisw/orr-portal/issues/130
If it would strengthen your proposal maybe shoot for service integration/resource sharing with COR. Evening running Widoco or pyLODE on the shared AWS instance?

**Comment by ashepherd** [comment]
That's a great idea!

**Comment by ashepherd** [comment]
@rduerr will contact Annie Burgess about the extent of the proposal writinng process. Ideas:

- SHACL shapes for validating markup
- Documenting the best practices and separating them out of the techie bits
- Providing guidance on schema.org markup for ontology documentation tools such as WIDOCO, pyLODE, and COR.

**Comment by nicholascar** [comment]
I've given Markdown generation from pyLODE a bash for 7 ontologies in a fork of sweet, see:

https://github.com/nicholascar/sweet/blob/master/src/human.md
https://github.com/nicholascar/sweet/blob/master/src/matr.md
https://github.com/nicholascar/sweet/blob/master/src/phen.md
https://github.com/nicholascar/sweet/blob/master/src/proc.md
https://github.com/nicholascar/sweet/blob/master/src/prop.md
https://github.com/nicholascar/sweet/blob/master/src/rela.md
https://github.com/nicholascar/sweet/blob/master/src/repr.md

I've done absolutely *no* tweaking - just running on default settings - and even so, the results look ok. I can think of much tidying-up, like removing empty table rows, catering for a few other commonly seen SWEET properties etc. and, if you're all interested, I could do this so we can run against all sweet.

**Comment by nicholascar** [comment]
Note that pyLODE understands a fair few schema.org ontology documentation properties, see https://github.com/RDFLib/pyLODE/blob/master/SNIPPETS.rst, but I am keen to cater for perceived best practice here so can always handle your preferred schema.org documentation.

**Comment by nicholascar** [comment]
I've added the ability for pyLODE to add schema.org metadata to all HTML outputs, as per https://github.com/RDFLib/pyLODE/issues/10. Early days so far but I'm keen to be guided by actual requirements before I speculatively just make it better.

**Comment by rduerr** [comment]
Still no word from Annie - I'll ping her again...

**Comment by rduerr** [comment]
Testbed proposal submitted - closing
