### ISSUE TITLE
What copyright or software licenses should be used 

### ISSUE THREAD

**Issue by rduerr** [ESIPFed/science-on-schema.org#60]
The documents and other resources generated by this cluster need to have copyright and/or software licenses attached.  

As examples, the schema.org schema is license under Creative Commons Attribution-ShareAlike License (version 3.0).  Meanwhile W3C documentation about ontologies such as DCAT-2 are copyright W3C and ontologies are licensed using https://www.w3.org/Consortium/Legal/2015/copyright-software-and-document

**Comment by mbjones** [comment]
Discussion at ESIP Winter proposed that we evaluate alternatives, including:

1. Using the SPDX URL directly
1. Use the SPDX License shortname directly 
1. Ingest the SPDX structure into an ontology in COR and use the COR URI
1. For licenses with well-known URIs (like Creative Commons), use the original license URI

Need to discuss and propose an approach.

**Comment by ashepherd** [comment]
Notes from ESIP Winter Meeting: https://docs.google.com/document/d/1ycG9Dlt6xRr9wxjqkQrPkJQJvm83E34eue_cxkrSGUI/edit?ts=5e1503e3#bookmark=id.x26mnoll110o

**Comment by mbjones** [comment]
Discussed and resolved licensing in issue #205, so closing this issue.
