### ISSUE TITLE
Recommendation on specifying dateModified for Datasets

### ISSUE THREAD

**Issue by datadavev** [ESIPFed/science-on-schema.org#67]
Knowledge of when a `SO:Dataset` resource or any of the components have changed is helpful for consumers to keep up to date with content changes. Harvesters should receive modification information early in harvesting workflows to make determinations of further work required. An end user of a Dataset should be informed of when a specific component of a Dataset might have been updated.

Modification dates can be specified in several locations, for example:

* Sitemap feed, e.g. `<lastmod>2019-01-01T21:14:10+00:00</lastmod>`
* Schema.org markup, e.g. `"dateModified":"2019-01-01T21:14:10+00:00"`
* Within referenced `SO:Dataset` components, e.g. somewhere in ISO metadata:  `<gco:DateTime>2019-01-01T21:14:10+00:00</gco:DateTime>` 

A suggested guideline for publishers:

1. Specific metadata date modified properties stored in data set components should be indicative of the modification date of the resource.
2. If specific components of a dataset are referenced by a `SO:Dataset`, then a `dateModified` property should be included in the reference to the resource. For example:
```
...
"@type":"Dataset",
"subjectOf":{
  "@id":"./metadata.xml",
  "@type": "MediaObject",
  "dateModified": "2019-01-01T21:14:10+00:00",
  "contentUrl": "https://mydata.org/dataset/metadata.xml",
  ...
}
...
```
3. The `lastmod` entry in a sitemap should be indicative of the most recent modified date that appears in the `SO:Dataset`
4. Header information returned in the HTTP request for the sitemap should be indicative of when the sitemap was last updated.

In all cases, dates should include timezone information.

**Comment by ashepherd** [comment]
Decision at ESIP Winter Meeting to add `dateModified` to the guidance docs for Datasets and all related data and metadata files.

See: https://docs.google.com/document/d/1ycG9Dlt6xRr9wxjqkQrPkJQJvm83E34eue_cxkrSGUI/edit?ts=5e1503e3#bookmark=id.d98whfcn9b84

**Comment by fils** [comment]
@datadavev , it would be good if this date in the JSON-LD was something the facility could use directly in creating the site.  I see you mentioning just that..   but I just wanted to add my +1 to this point.  

Sitemaps follow:  
https://www.w3.org/TR/NOTE-datetime

This way facilities could use this for generating the sitemaps.
