### ISSUE TITLE
v1.1 Release

### ISSUE THREAD

**Issue by ashepherd** [ESIPFed/science-on-schema.org#93]
## FIXES
- Using `@type` instead of `schema:additionalType` ([decision](decisions/74-schemaorg-additionalType-vs-RDF-typing.md), Issue #74)

## IMPROVEMENTS
- Use `schema:PropertyValue` for describing Persistent Identifiers ([decision](decisions/13-schemaorg-identifier-as-PropertyValue.md), Issue #13) 
    - [Guide: Dataset - Identifier](guides/Dataset.md#identifier)
    - [Guide: Data Repository- Identifier](guides/DataRepository.md#identifier)
- Use SPDX URLs for Dataset License ([decision](decisions/47-use-spdx-licenses.md), Issue #47)
    - [Guide: Dataset - License](guides/Dataset.md#license)

## NEW FEATURES
- Describing Dataset Metadata files ([decision](decisions/4-dataset-metadata-distributions.md), Issue #4)
    - [Guide: Dataset - Metadata Files](guides/Dataset.md#metadata)
- Gitflow Release Workflow ([decision](decisions/30-release-workflow.md), Issue #30)
    - [CONTRIBUTING.md](CONTRIBUTING.md)
------------

- [x] Provide links to the stable (latest version)
- [x] Make it clear how to find the develop branch and the upcoming version release
- [x] Reserve a Zenodo DOI (and update authors)
- [x] Gather ORCIDs for all contributors for inclusion at Zenodo DOI.
- [x] Update the Zenodo DOIs ( https://github.com/ESIPFed/science-on-schema.org#version-dois )
- [x] Update the README (make it clear what version it is)
- [x] Make an Announcement!! (mailing list & ESIP All)

**Comment by ashepherd** [comment]
@datadavev @mbjones @rduerr can you comment here with your ORCIDs so I can add you as authors on the v1.1 release?

**Comment by rduerr** [comment]
https://orcid.org/0000-0003-4808-4736 is mine - I'll take a look at yesterday's changes tomorrow!

**Comment by datadavev** [comment]
My ORCID is https://orcid.org/0000-0002-6513-4996
cheers

**Comment by mbjones** [comment]
Mine is: https://orcid.org/0000-0003-0077-4738

**Comment by charlesvardeman** [comment]
MIne is: https://orcid.org/0000-0003-4091-6059

**Comment by ashepherd** [comment]
Tag: 7511839b00ebb028451a1198870898a041a76cbe
