### ISSUE TITLE
Register IGSN at identifiers.org

### ISSUE THREAD

**Issue by ashepherd** [ESIPFed/science-on-schema.org#98]
Related to #13 & #94,I've submitted the request to have IGSN added to identifiers.org. The editor knows it was coming and it sounded like it should be added shortly. Will attach to Milestone v1.2 if it doesn't happen soon.

**Comment by ashepherd** [comment]
Response from identifiers.org:
```
Dear ADAM SHEPHERD,

At identifiers.org we would like to confirm that your prefix registration request for

---
Prefix Name: International Geo Sample Number
Preferred Prefix: igsn
Description:
The IGSN is an alphanumeric code that uniquely identifies samples taken from our natural environment (for example: rock specimens, water samples, sediment cores), as well as related sampling features (sites, stations, stratigraphic sections, etc.). Except in special cases*, IGSNs obtained from SESAR are 9 characters long. IGSNs obtained from allocating agents other than SESAR may have different syntax, but all are guaranteed to be globally unique via a central registry.
---

Has been received and queued for processing.

We would like to thank you for the confidence deposited in identifiers.org.

Please, allow a few days for your request to be processed.

Kind Regards,
Identifiers.org Team
```

**Comment by ashepherd** [comment]
Should update section `Attaching Physical Samples to a Dataset` of Dataset guide

https://github.com/ESIPFed/science-on-schema.org/blob/feature_13_specifying_identifiers/guides/Dataset.md#attaching-physical-samples-to-a-dataset

**Comment by mbjones** [comment]
@ashepherd I just checked and am not seeing IGSN in the https://identifiers.org registry yet. Maybe we should ping them again and see if there is an issue to be resolved.

**Comment by ashepherd** [comment]
thanks, just pinged `curator@identifiers.org`

**Comment by ashepherd** [comment]
IGSN has been registered: https://registry.identifiers.org/registry/igsn
